version: '3.1'
services:
  db:
    image: mysql:latest
    container_name: ObligatorioBDContainer
    ports:
      - "3030:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ObligatorioBDContainer
      MYSQL_DATABASE: escuela_de_deportes  # Base de datos a crear
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
    container_name: ObligatorioAPIContainer
    build: .
    command: uvicorn API.app:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ObligatorioBDContainer
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: escuela_de_deportes

      ADMIN_CI: 12345678
      ADMIN_PASSWORD: 12345678
      ADMIN_NOMBRE: Admin
      ADMIN_APELLIDO: Admin
      ADMIN_FECHA_NAC: 2024/10/24
      ADMIN_CEL: 0914123886
      ADMIN_CORREO: adminadmin@gmail.com