version: '3.1'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: ObligatorioBDContainer
    ports:
    - "3030:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ObligatorioBDContainer